"use strict";
(function () {
  const STORAGE_KEY = "upgrade-pathfinder-v1";
  const MIGRATION_KEY = "upgrade-pathfinder-migrated-away-from-sss-v1";
  const TIER_ORDER = ["D", "C", "B", "A", "S", "SS"];
  const RANKS = [...["D", "C", "B", "A", "S", "SS"].flatMap((tier) => [1,2,3,4].map((rank) => ({name:`${tier}${rank}`,tier,rank}))),{name:"SSS",tier:"SSS",rank:1}];
  const DEFAULT_FORMULAS = {baseEquip:10.2,baseH1:1.01,baseH2:15.78125,baseH3:6.3125,equipGrowth:1.02,holdingGrowth:1.01};
  function savedState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")||{}}catch{return{}}}
  function saveState(s){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}catch{}}
  function rankIndex(n){return RANKS.findIndex(r=>r.name===n)}
  function ownedRanks(n){return RANKS.slice(0,rankIndex(n)+1)}
  function migrateStaleSSSSelection(){const s=savedState();if(s.equippedRank==="SSS"){s.equippedRank="SS2";saveState(s);const e=document.querySelector("#equipped-rank");if(e){e.value="SS2";e.dispatchEvent(new Event("change",{bubbles:true}))}}try{localStorage.setItem(MIGRATION_KEY,"1")}catch{}}
  function moveEquippedStat(){const summary=document.querySelector("#equipped-stat"),body=document.querySelector("#items-body"),select=document.querySelector("#equipped-rank");if(!summary||!body||!select)return;summary.style.display="none";const text=summary.textContent.replace(/^Equipped stat:\s*/i,"").trim();if(!text||text==="—")return;const row=[...body.querySelectorAll("tr")].find(tr=>tr.querySelector(`input[data-rank="${select.value}"]`));if(!row)return;const cell=row.querySelector("td:first-child");if(!cell)return;cell.querySelector(".equipped-pill")?.remove();cell.querySelector(".equipped-stat-inline")?.remove();const stat=document.createElement("span");stat.className="equipped-stat-inline";stat.textContent=text;cell.appendChild(stat)}
  function rankFactor(r){if(r.tier==="SSS")return 625*2**3*2.5**4*12.5;if(["D","C","B","A"].includes(r.tier))return 5**TIER_ORDER.indexOf(r.tier)*1.5**(r.rank-1);if(r.tier==="S")return 625*2**(r.rank-1);return 625*2**3*2.5**r.rank}
  function itemStats(n,l,f){const r=RANKS[rankIndex(n)],m=rankFactor(r),hg=f.holdingGrowth**(l-1);return{equip:f.baseEquip*m*f.equipGrowth**(l-1),h1:f.baseH1*m*hg,h2:rankIndex(n)>=rankIndex("S1")?f.baseH2*(m/rankFactor(RANKS[rankIndex("S1")]))*hg:0,h3:rankIndex(n)>=rankIndex("SS1")?f.baseH3*(m/rankFactor(RANKS[rankIndex("SS1")]))*hg:0}}
  function roundHalfDown(v,d=2){const f=10**d,a=Math.abs(v)*f,w=Math.floor(a),fr=a-w;return Math.sign(v)*(fr>.5+1e-10?w+1:w)/f}
  function gameStatValue(v){const a=Math.abs(v);if(!a)return{numeric:0};let d;if(a>=1e15)d=10**(Math.floor(Math.log10(a)/3)*3);else if(a>=1e12)d=1e12;else if(a>=1e9)d=1e9;else if(a>=1e6)d=1e6;else if(a>=1e3)d=1e3;else d=1;let n=roundHalfDown(v/d);if(Math.abs(n)>=1000&&d>1){d*=1000;n=roundHalfDown(v/d)}return{numeric:n*d}}
  function damageTotal(levels,equipped,formulas,raw){let h1=0,h2=0,h3=0;ownedRanks(equipped).forEach(r=>{const s=itemStats(r.name,Number(levels[r.name]||1),formulas);h1+=raw?s.h1:gameStatValue(s.h1).numeric;h2+=raw?s.h2:gameStatValue(s.h2).numeric;h3+=raw?s.h3:gameStatValue(s.h3).numeric});const e=itemStats(equipped,Number(levels[equipped]||1),formulas).equip;return(1+e/100)*(1+h1/100)*(1+h2/100)*(1+h3/100)}
  function costAt(costs,l){const c=Number(costs[l]);return Number.isFinite(c)&&c>0?c:null}
  function readCostTable(){const s=savedState(),costs={...(s.costs||{})},ta=document.querySelector("#cost-data");if(ta?.value?.trim())ta.value.split(/\r?\n/).forEach(line=>{const m=line.trim().match(/^(\d+)\s*(?:,|\t|\s+)\s*([0-9.]+)\s*([kKmMbB]?)$/);if(!m)return;const a=Number(m[2]),u=m[3].toLowerCase(),x=a*(u==="k"?1e3:u==="m"?1e6:u==="b"?1e9:1);if(Number.isFinite(x)&&x>0)costs[Number(m[1])]=x});return costs}
  function currentBuildFromPage(equipped){const levels={},body=document.querySelector("#items-body");body?.querySelectorAll("input[data-rank]").forEach(i=>{levels[i.dataset.rank]=Math.max(1,Math.min(500,Math.round(Number(i.value)||1)))});const e=document.querySelector("#equipped-level");if(e)levels[equipped]=Math.max(1,Math.min(500,Math.round(Number(e.value)||1)));return levels}
  function upgradeAction(n,levels,equipped,costs,formulas,raw){const from=Number(levels[n]||1),to=from+1,cost=to<=500?costAt(costs,to):null;if(!cost)return null;const before=damageTotal(levels,equipped,formulas,raw),after=damageTotal({...levels,[n]:to},equipped,formulas,raw),gain=((after-before)/before)*100;return{rank:n,fromLevel:from,toLevel:to,cost,percentGain:gain,efficiency:gain/cost}}
  function optimizeTarget(target,targetLevel,equipped,costs,formulas,raw){const levels=Object.fromEntries(ownedRanks(equipped).map(r=>[r.name,1]));levels[target]=targetLevel;const lowers=ownedRanks(equipped).filter(r=>r.name!==target),upgrades=[];for(let safety=0;safety<5000;safety++){const t=upgradeAction(target,levels,equipped,costs,formulas,raw);if(!t)return null;const best=lowers.map(r=>upgradeAction(r.name,levels,equipped,costs,formulas,raw)).filter(Boolean).sort((a,b)=>b.efficiency-a.efficiency||rankIndex(b.rank)-rankIndex(a.rank))[0];if(!best||best.efficiency<=t.efficiency*(1+1e-12))break;levels[best.rank]++;upgrades.push(best)}return{levels,upgrades}}
  function formatNumber(v,digits=4){if(!Number.isFinite(v))return"—";if(v===0)return"0";const a=Math.abs(v),s=[[1e15,"Q"],[1e12,"T"],[1e9,"B"],[1e6,"M"],[1e3,"k"]],f=s.find(([t])=>a>=t);if(f){const[t,u]=f;return`${(v/t).toLocaleString(undefined,{maximumSignificantDigits:digits})}${u}`}return v.toLocaleString(undefined,{maximumSignificantDigits:digits,maximumFractionDigits:3})}
  function syncBuildStateFromControls(){const select=document.querySelector("#equipped-rank"),input=document.querySelector("#equipped-level");if(!select||!input)return;const rank=select.value,live=Math.max(1,Math.min(500,Math.round(Number(input.value)||1)));select.dispatchEvent(new Event("change",{bubbles:true}));const after=document.querySelector("#equipped-level");if(after){after.value=String(live);after.dispatchEvent(new Event("change",{bubbles:true}))}}
  function buildIndependentRoute(){syncBuildStateFromControls();const select=document.querySelector("#equipped-rank"),equipped=select?.value||savedState().equippedRank||"SS2",levels=currentBuildFromPage(equipped),start=Number(levels[equipped]||1),out=document.querySelector("#planner-output");if(!out)return;if(start>=500){out.innerHTML=`<div class="plan-summary"><h3>${equipped} is already at level 500</h3><p>There are no equipped levels left to route.</p></div>`;return}const saved=savedState(),costs=readCostTable(),formulas={...DEFAULT_FORMULAS,...(saved.formulas||{})},toggle=document.querySelector("#use-raw-holding-totals"),raw=toggle?toggle.checked:Boolean(saved.options?.useRawHoldingTotals),rows=[];for(let target=start;target<500;target++){const plan=optimizeTarget(equipped,target,equipped,costs,formulas,raw);if(!plan)break;const changes=[],prep=plan.upgrades.length;let prepCost=0;for(const r of ownedRanks(equipped)){if(r.name===equipped)continue;const optimal=Number(plan.levels[r.name]||1);if(optimal<=1)continue;changes.push(`${r.name} 1→${optimal}`);for(let l=2;l<=optimal;l++){const c=costAt(costs,l);if(c)prepCost+=c}}const text=changes.length?changes.join(", "):"no preparatory lower upgrades";rows.push(`<div class="route-row"><strong>Before ${equipped} ${target} → ${target+1}</strong> — ${text} <span class="quiet">(${prep} prep upgrade${prep===1?"":"s"}, ${formatNumber(prepCost)})</span></div>`)}if(!rows.length){out.innerHTML=`<div class="plan-summary"><h3>No route could be calculated</h3><p>The next equipped-item cost is not known yet.</p></div>`;return}out.innerHTML=`<div class="plan-summary"><h3>Independent ${equipped} route</h3><p>Each equipped level is recalculated independently from level 1 on the lower items, so a later target can legitimately call for lower holding-item levels than an earlier target.</p><div class="route-list">${rows.join("")}</div></div>`}
  function install(){migrateStaleSSSSelection();moveEquippedStat();const body=document.querySelector("#items-body");if(body)new MutationObserver(()=>moveEquippedStat()).observe(body,{childList:true,subtree:true});document.querySelector("#equipped-rank")?.addEventListener("change",()=>setTimeout(moveEquippedStat,0));document.querySelector("#equipped-level")?.addEventListener("change",()=>setTimeout(moveEquippedStat,0));document.querySelector("#use-raw-holding-totals")?.addEventListener("change",()=>setTimeout(moveEquippedStat,0));document.querySelector("#refresh-results")?.addEventListener("click",()=>setTimeout(moveEquippedStat,0));const b=document.querySelector("#build-equipped-route");if(b)b.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();buildIndependentRoute()},true)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install);else install();
})();
